<?php


/**
 * This class defines the structure of the 'horaire' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar 17 20:31:07 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class HoraireTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.HoraireTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('horaire');
		$this->setPhpName('Horaire');
		$this->setClassname('Horaire');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addForeignKey('TRAJET_ID', 'TrajetId', 'INTEGER', 'trajet', 'ID', true, null, null);
		$this->addForeignKey('LIGNE_ID', 'LigneId', 'INTEGER', 'ligne', 'ID', true, null, null);
		$this->addForeignKey('GARE_ID', 'GareId', 'INTEGER', 'gare', 'ID', true, null, null);
		$this->addColumn('HEURE', 'Heure', 'TIME', true, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Trajet', 'Trajet', RelationMap::MANY_TO_ONE, array('trajet_id' => 'id', ), null, null);
    $this->addRelation('Ligne', 'Ligne', RelationMap::MANY_TO_ONE, array('ligne_id' => 'id', ), null, null);
    $this->addRelation('Gare', 'Gare', RelationMap::MANY_TO_ONE, array('gare_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // HoraireTableMap
