# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  displayed_messages_amount: 3
  message_max_length: 140
  displayed_discussions_amount: 4
  discussion_max_length: 40
