<?php


/**
 * Skeleton subclass for performing query and update operations on the 'ligne_gare' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 19 09:19:29 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LigneGarePeer extends BaseLigneGarePeer {

} // LigneGarePeer
