<?php


/**
 * Skeleton subclass for performing query and update operations on the 'message' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Mar 19 09:24:02 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MessagePeer extends BaseMessagePeer {

    const SAFETY_AMOUNT = 200;

    static public function getMessagesFromDiscussion($discussionId, $chronologicalOrder = true, $newerMessageId=null, $olderMessageId=null, $amount=0, $safety=true)
    {
        $c = new Criteria();
        $c->add(self::DISCUSSION_ID, $discussionId);
        $c->add(self::VALIDE, 1);
        if(!is_null($newerMessageId) && $newerMessageId > 0)
        {
            $c->add(self::ID, $newerMessageId, Criteria::LESS_EQUAL);
        }
        if(!is_null($olderMessageId) && $olderMessageId > 0)
        {
            $c->add(self::ID, $olderMessageId, Criteria::GREATER_EQUAL);
        }
        if($chronologicalOrder)
        {
            $c->addAscendingOrderByColumn(self::CREATED_AT);
        }
        else
        {
            $c->addDescendingOrderByColumn(self::CREATED_AT);
        }
        if($safety && $amount > self::SAFETY_AMOUNT)
        {
            $amount = self::SAFETY_AMOUNT;
        }
        else if($amount > 0)
        {
            $c->setLimit($amount);
        }
        return self::doSelect($c);
    }
} // MessagePeer
