<?php


/**
 * Skeleton subclass for representing a row from the 'trajet' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar 17 20:30:21 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Trajet extends BaseTrajet {

} // Trajet
